/**
 * Chép từ `mes-backend/app/common/vocab/error_codes.py`.
 *
 * FE rẽ nhánh bằng `code`, KHÔNG bằng `message` — message là câu tiếng Việt
 * cho người vận hành và có thể sửa bất cứ lúc nào (R12).
 */
export const ERR = {
  DOMAIN: "DOMAIN", NOT_FOUND: "NOT_FOUND", INVALID: "INVALID", FORBIDDEN: "FORBIDDEN",

  MO_CODE: "MO_CODE", MO_DUPLICATE: "MO_DUPLICATE", ALREADY_SUBMITTED: "ALREADY_SUBMITTED",
  CANCEL_REASON: "CANCEL_REASON", MO_LOCKED: "MO_LOCKED",

  ROUND_OPEN: "ROUND_OPEN", STEP_DUP: "STEP_DUP", SKIP_STEP: "SKIP_STEP",
  NO_HANDOVER: "NO_HANDOVER", NO_QC: "NO_QC", QC_FAILED: "QC_FAILED",
  NO_PRODUCTION: "NO_PRODUCTION", NO_PACKING: "NO_PACKING",

  NO_WAREHOUSE_OUT_ACCEPT: "NO_WAREHOUSE_OUT_ACCEPT", HANDED_OVER: "HANDED_OVER",
  NO_QC_ACCEPT: "NO_QC_ACCEPT", QC_DONE: "QC_DONE", QC_REASON: "QC_REASON",

  NO_PRODUCTION_ACCEPT: "NO_PRODUCTION_ACCEPT", NO_LINE: "NO_LINE", LINE_ADDED: "LINE_ADDED",
  LINE_RUNNING: "LINE_RUNNING", LINE_NOT_RUNNING: "LINE_NOT_RUNNING", LINE_BUSY: "LINE_BUSY",
  HOLD_REASON: "HOLD_REASON", SEG_OPEN: "SEG_OPEN",

  PROD_EMPTY: "PROD_EMPTY", PROD_CLOSED: "PROD_CLOSED", PROD_BALANCE: "PROD_BALANCE",
  NG_REASON: "NG_REASON", SHORT_REASON: "SHORT_REASON",

  NOT_RUNNING: "NOT_RUNNING", HOURLY_DUP: "HOURLY_DUP", HOURLY_QTY: "HOURLY_QTY",
  HOURLY_OVER: "HOURLY_OVER", HOURLY_PEOPLE: "HOURLY_PEOPLE", HOURLY_TARGET: "HOURLY_TARGET",

  NO_RUN: "NO_RUN", PACK_STARTED: "PACK_STARTED", NO_PACK: "NO_PACK", PACK_DONE: "PACK_DONE",
  PACK_OVER_OK: "PACK_OVER_OK", PACK_BEFORE_PROD: "PACK_BEFORE_PROD",
  NO_PCS_PER_BOX: "NO_PCS_PER_BOX", BOX_DUP: "BOX_DUP", BOX_OVER_MADE: "BOX_OVER_MADE",

  NO_WAREHOUSE_IN_ACCEPT: "NO_WAREHOUSE_IN_ACCEPT", WAREHOUSE_IN_DONE: "WAREHOUSE_IN_DONE",
  SCAN_READ: "SCAN_READ", DB: "DB",
} as const;

export type ErrCode = (typeof ERR)[keyof typeof ERR];
